### ISSUE TITLE
Automatically install dependencies

### ISSUE THREAD

**Issue by jokervTv** [Haiquan-27/SSH-Panel#1]
非常好的插件！是否考虑通过自动下载的方式，实现自动安装依赖呢？

Thanks for your work.

**Comment by Haiquan-27** [comment]
一些python依赖确实可以通过向插件发布通道发布以实现自动安装，但是对于系统级的依赖（例如ubuntu上的`libffi-dev`）无法提供自动安装的方法，在插件中如果缺少依赖会提示缺少的部分，用户按照引导自行安装将不会产生额外的麻烦。

Some Python libs can indeed be automatically installed by publishing to the plugin release channel, but for system dependencies (such as `libffi-dev` on Ubuntu), automatic installation methods cannot be provided. If a dependency is missing in the plugin, it will prompt the missing part, and Users who follow the instructions to install on their own will not encounter any additional trouble.
