### ISSUE TITLE
无法修改远程机器的原文件，只能将修改后的文件副本保存到本地

### ISSUE THREAD

**Issue by 152300014** [Haiquan-27/SSH-Panel#2]
您好，使用SSH-Panel打开远程linux下的文件，修改保存后会在本地local_path下生成一份副本，但是远程机器下文件未进行修改。
请问是设计如此吗？之后是否会添加同步修改远程文件的功能吗？

**Comment by Haiquan-27** [comment]
不是的，这可能是个bug，请你使用package control安装最新的版本，正常情况会在保存时弹出一个input panel，确认保存的远程文件路径，回车确认后即可正常保存
![image](https://github.com/user-attachments/assets/64d1161c-625d-48d2-9eab-84d1803ef0cb)

**Comment by Haiquan-27** [comment]
配置文件中的remote_path路径值设置不标准可能会造成此问题的发生，如果问题未解决，请提供你的配置文件(ssh-panel.sublime-settings)以及或console异常输出，我将尝试修复

**Comment by Haiquan-27** [comment]
过去的版本(<=v1.3.0)确实存在过这个问题，现在最新的版本v1.3.1已经修复了这个错误
